"""create backtests table

Revision ID: 56c9fd79e741
Revises: 08d19b582c1b
Create Date: 2026-07-01 18:21:08.042088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c9fd79e741'
down_revision: Union[str, Sequence[str], None] = '08d19b582c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('pair', sa.String(length=7), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('final_balance', sa.Float(), nullable=False),
    sa.Column('trades_taken', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('profitable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtests')
    # ### end Alembic commands ###
